"""rename role name from user_manager to manager

Revision ID: 8ab2c2fca3c2
Revises: f13098ed1c5c
Create Date: 2023-06-11 01:00:39.561689

"""


# revision identifiers, used by Alembic.
revision = "8ab2c2fca3c2"
down_revision = "f13098ed1c5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
