exclude: 'docs|node_modules|migrations|.git|.tox|.md'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: 'v0.5.0'
    hooks:
    - id: remove-print-statements
      args: ['--verbose']   # Show all the print statements to be removed

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo:  https://github.com/pycqa/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort]
