"""edit the user_id field to include ondelete

Revision ID: 553db079bd70
Revises: 8eb1d287aaf4
Create Date: 2023-06-11 23:30:38.059414

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = "553db079bd70"
down_revision = "8eb1d287aaf4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tmp_calorie_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("number_of_calories", sa.Integer()),
        sa.Column("is_below_expected", sa.Boolean()),
        sa.Column("created_at", sa.DateTime(), default=datetime.utcnow),
        sa.Column("updated_at", sa.DateTime(), default=datetime.utcnow),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute("INSERT INTO tmp_calorie_entries SELECT * FROM calorie_entries")

    op.drop_table("calorie_entries")

    op.rename_table("tmp_calorie_entries", "calorie_entries")
    # op.drop_constraint(None, 'calorie_entries', type_='foreignkey')
    # op.create_foreign_key(None, 'calorie_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.create_table(
        "tmp_calorie_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("number_of_calories", sa.Integer()),
        sa.Column("is_below_expected", sa.Boolean()),
        sa.Column("created_at", sa.DateTime(), default=datetime.utcnow),
        sa.Column("updated_at", sa.DateTime(), default=datetime.utcnow),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute("INSERT INTO tmp_calorie_entries SELECT * FROM calorie_entries")

    op.drop_table("calorie_entries")

    op.rename_table("tmp_calorie_entries", "calorie_entries")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'calorie_entries', type_='foreignkey')
    # op.create_foreign_key(None, 'calorie_entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
