"""add user column from CalorieEntry table

Revision ID: a989d77059a9
Revises: dd299db88dda
Create Date: 2023-06-11 22:55:12.212134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a989d77059a9'
down_revision = 'dd299db88dda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
