"""add cascade parameter to the relationship definition

Revision ID: becb51b15273
Revises: 6f7b10ff2ca0
Create Date: 2023-06-11 21:06:12.374310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becb51b15273'
down_revision = '6f7b10ff2ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
