"""remove user column from CalorieEntry table

Revision ID: dd299db88dda
Revises: becb51b15273
Create Date: 2023-06-11 22:53:23.073479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd299db88dda"
down_revision = "becb51b15273"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
