"""Add expected_calories column

Revision ID: eab3f2ac8ef7
Revises: eff37e8b8b29
Create Date: 2023-06-12 13:16:51.399122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab3f2ac8ef7'
down_revision = 'eff37e8b8b29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
