# Generated by Django 4.2.2 on 2023-06-11 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaloryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calory_limit', models.FloatField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('exceeded_maximum', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('present_calory_amount', models.FloatField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calory Limit',
                'ordering': ('created_at',),
            },
        ),
    ]
