# Generated by Django 4.2.2 on 2023-06-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_calo',
            field=models.IntegerField(null=True),
        ),
    ]
