# Generated by Django 4.2.2 on 2023-06-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_user_daily_calo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_calo',
            field=models.IntegerField(),
        ),
    ]
