# Generated by Django 4.2.2 on 2023-06-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_calo_calories_alter_calo_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calo',
            old_name='Calories',
            new_name='calories',
        ),
    ]
