# Generated by Django 4.2.2 on 2023-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
