# Generated by Django 4.2.2 on 2023-06-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='daily_Cola',
            new_name='daily_Calo',
        ),
    ]
