# Generated by Django 4.2.2 on 2023-06-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorylimit',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
