# Generated by Django 4.2.2 on 2023-06-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_alter_calorylimit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorylimit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
