# Generated by Django 4.2.2 on 2023-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0004_calorylimit_present_calory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
