# Generated by Django 4.2.2 on 2023-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_alter_calories_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calories',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Calories'},
        ),
        migrations.AlterModelOptions(
            name='calorylimit',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Calory Limit'},
        ),
        migrations.AddField(
            model_name='calorylimit',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
