# Generated by Django 4.2.2 on 2023-06-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calory_limit', '0001_initial'),
        ('calories', '0006_alter_calories_options_alter_calorylimit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='calory_limit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calory_limit.calorylimit'),
        ),
        migrations.DeleteModel(
            name='CaloryLimit',
        ),
    ]
