# Generated by Django 4.1.2 on 2023-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_entry_date_alter_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='calories',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
