# Generated by Django 4.2.2 on 2023-06-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_entry_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="is_below_daily_calories_threshold",
            field=models.BooleanField(default=True),
        ),
    ]
