# Generated by Django 4.2.2 on 2023-06-12 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_entry_is_below_daily_calories_threshold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="is_below_daily_calories_threshold",
            new_name="below_daily_threshold",
        ),
    ]
