# Generated by Django 4.1.2 on 2023-06-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_entry_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_calories_below_expected',
            field=models.BooleanField(default=False),
        ),
    ]
