# Generated by Django 4.1.2 on 2023-06-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_entry_is_calories_below_expected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_calories_below_expected',
            field=models.BooleanField(default=True),
        ),
    ]
