# Generated by Django 4.2.2 on 2023-06-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calori', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calo',
            name='limt_reach',
            field=models.BooleanField(default=False),
        ),
    ]
