# Generated by Django 4.1.2 on 2023-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expected_calories',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user_manager', 'User Manager'), ('regular_user', 'Regular User')], default='regular_user', max_length=20),
        ),
    ]
