# Generated by Django 4.2.2 on 2023-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="expected_daily_calories",
            field=models.DecimalField(decimal_places=2, default=2250, max_digits=10),
        ),
    ]
