# Generated by Django 3.2.15 on 2023-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=25),
        ),
    ]
