# Generated by Django 3.2.15 on 2023-06-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calories_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
